### ISSUE TITLE
"libguile.h" missing

### ISSUE THREAD

**Issue by miroi** [alexei-matveev/paragauss-gpl#2]
Dear experts,

thanks for allowing the ParaGauss software. I am trying to compile it according to the "paragauss-gpl/Makefile" instructions.

Could you please give me hints on how to fix missing  lib ?

```
milias@lxir074.gsi.de:~/Work/qch/software/paragauss-gpl/.make -r
make: guile-config: Command not found
( cd guile; rm -f guile-qm.o ; mpicc -c  -I/u/milias/Work/qch/software/paragauss-gpl/comm/mpi_dir -I/usr/include/mpi /cvmfs/it.gsi.de/compiler/intel/15.0/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_scalapack_lp64.a -Wl,--start-group /cvmfs/it.gsi.de/compiler/intel/15.0/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_intel_lp64.a /cvmfs/it.gsi.de/compiler/intel/15.0/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_core.a /cvmfs/it.gsi.de/compiler/intel/15.0/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_sequential.a -Wl,--end-group /cvmfs/it.gsi.de/compiler/intel/15.0/composer_xe_2015.2.164/mkl/lib/intel64/libmkl_blacs_openmpi_lp64.a -lpthread -lm  guile-qm.c -o guile-qm.o; test -f guile-qm.o )
guile-qm.c(29): catastrophic error: cannot open source file "libguile.h"
  #include <libguile.h>
                       ^

compilation aborted for guile-qm.c (code 4)
make: *** [guile/guile-qm.o] Error 1
milias@lxir074.gsi.de:~/Work/qch/software/paragauss-gpl/.
```

**Comment by alexei-matveev** [comment]
You probably solved that already, but for the record: your system is possibly missing header files usually distributed in *-dev or *-devel packages separately from the link- or run-time libraries. On ubuntu 14.04 the package name is:

```
guile-2.0-dev
```

guile-config is a helper program that outputs compiler flags for compilation and linking. If this is a machine you dont have control of it is probably easier to disable that altogether. I tried to keep the option with WITH_GUILE = 0 working. I would not recommend compiling and installing guile from sources yourself.

**Comment by miroi** [comment]
Thanks for the hint, closing this issue.
